'use client'

import { useState } from 'react'

import {
  ChevronDown,
  ChevronRight,
  Download,
  Plus,
  Send,
  CheckCircle2,
  Clock,
  DollarSign,
  FileText,
  Sparkles,
  type Calendar,
  TrendingUp,
  Percent,
  Building2,
  FileCheck,
  AlertTriangle,
  Eye,
  Camera,
  Layers,
  ArrowRightLeft,
  RotateCcw,
} from 'lucide-react'

import { FilterBar } from '@/components/skeleton/filter-bar'
import { AIFeaturesPanel } from '@/components/skeleton/ui'
import { useFilterState, matchesSearch, sortItems } from '@/hooks/use-filter-state'
import { cn } from '@/lib/utils'

type DrawStatus = 'draft' | 'internal_review' | 'approved_internal' | 'submitted' | 'lender_review' | 'revision_requested' | 'approved' | 'disbursed' | 'paid'

interface DrawSupportingDocs {
  lienWaivers: { required: number; received: number }
  photos: number
  inspections: { required: boolean; completed: boolean }
  invoiceBackup: number
}

interface Draw {
  id: string
  drawNumber: number
  projectName: string
  milestone: string
  amount: number
  retainageAmount: number
  netAmount: number
  previousBilled: number
  totalCompleted: number
  percentComplete: number
  status: DrawStatus
  applicationDate: string
  periodFrom: string
  periodTo: string
  description?: string
  aiNote?: string
  formatType: 'aia_g702' | 'custom' | 'lender_specific'
  lenderName?: string
  submittedMethod?: 'portal' | 'email' | 'physical'
  approvedAmount?: number
  disbursedAmount?: number
  variance?: number
  sovLineCount: number
  changeOrdersIncluded: number
  supportingDocs: DrawSupportingDocs
  revisionNumber?: number
  autoGenerated: boolean
  storedMaterials: number
  contractAmount: number
}

const mockDraws: Draw[] = [
  {
    id: '1',
    drawNumber: 1,
    projectName: 'Smith Residence',
    milestone: 'Contract Signing',
    amount: 245000,
    retainageAmount: 24500,
    netAmount: 220500,
    previousBilled: 0,
    totalCompleted: 245000,
    percentComplete: 10,
    status: 'paid',
    applicationDate: '2024-10-15',
    periodFrom: '2024-10-01',
    periodTo: '2024-10-31',
    description: 'Initial deposit upon contract execution',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    submittedMethod: 'portal',
    approvedAmount: 245000,
    disbursedAmount: 220500,
    sovLineCount: 15,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 0, received: 0 }, photos: 0, inspections: { required: false, completed: false }, invoiceBackup: 0 },
    autoGenerated: false,
    storedMaterials: 0,
    contractAmount: 2450000,
  },
  {
    id: '2',
    drawNumber: 2,
    projectName: 'Smith Residence',
    milestone: 'Foundation Complete',
    amount: 367500,
    retainageAmount: 36750,
    netAmount: 330750,
    previousBilled: 245000,
    totalCompleted: 612500,
    percentComplete: 25,
    status: 'disbursed',
    applicationDate: '2024-11-08',
    periodFrom: '2024-11-01',
    periodTo: '2024-11-30',
    description: 'Pilings, grade beams, and slab complete',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    submittedMethod: 'portal',
    approvedAmount: 367500,
    disbursedAmount: 330750,
    sovLineCount: 15,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 4, received: 4 }, photos: 8, inspections: { required: true, completed: true }, invoiceBackup: 6 },
    autoGenerated: false,
    storedMaterials: 0,
    contractAmount: 2450000,
  },
  {
    id: '3',
    drawNumber: 3,
    projectName: 'Smith Residence',
    milestone: 'Framing Complete',
    amount: 490000,
    retainageAmount: 49000,
    netAmount: 441000,
    previousBilled: 612500,
    totalCompleted: 1102500,
    percentComplete: 45,
    status: 'approved',
    applicationDate: '2024-12-12',
    periodFrom: '2024-12-01',
    periodTo: '2024-12-31',
    description: 'Structural framing and roof sheathing',
    aiNote: 'Approved 2 days faster than average. Lender inspection passed with no adjustments.',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    submittedMethod: 'email',
    approvedAmount: 490000,
    sovLineCount: 18,
    changeOrdersIncluded: 1,
    supportingDocs: { lienWaivers: { required: 7, received: 7 }, photos: 15, inspections: { required: true, completed: true }, invoiceBackup: 12 },
    autoGenerated: false,
    storedMaterials: 18500,
    contractAmount: 2510000,
  },
  {
    id: '4',
    drawNumber: 4,
    projectName: 'Smith Residence',
    milestone: 'Dried In',
    amount: 367500,
    retainageAmount: 36750,
    netAmount: 330750,
    previousBilled: 1102500,
    totalCompleted: 1470000,
    percentComplete: 60,
    status: 'lender_review',
    applicationDate: '2025-01-05',
    periodFrom: '2025-01-01',
    periodTo: '2025-01-31',
    description: 'Windows, doors, and roofing installed',
    aiNote: 'Pending bank inspection - typically 3-5 days. Inspector assigned: Tom Williams.',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    submittedMethod: 'portal',
    sovLineCount: 18,
    changeOrdersIncluded: 1,
    supportingDocs: { lienWaivers: { required: 8, received: 6 }, photos: 18, inspections: { required: true, completed: false }, invoiceBackup: 14 },
    autoGenerated: true,
    storedMaterials: 22000,
    contractAmount: 2510000,
  },
  {
    id: '5',
    drawNumber: 5,
    projectName: 'Smith Residence',
    milestone: 'MEP Rough Complete',
    amount: 367500,
    retainageAmount: 36750,
    netAmount: 330750,
    previousBilled: 1470000,
    totalCompleted: 1837500,
    percentComplete: 75,
    status: 'draft',
    applicationDate: '2025-02-01',
    periodFrom: '2025-02-01',
    periodTo: '2025-02-28',
    description: 'Electrical, plumbing, and HVAC rough-in',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    sovLineCount: 18,
    changeOrdersIncluded: 2,
    supportingDocs: { lienWaivers: { required: 9, received: 3 }, photos: 6, inspections: { required: true, completed: false }, invoiceBackup: 8 },
    autoGenerated: true,
    storedMaterials: 15000,
    contractAmount: 2570000,
  },
  {
    id: '6',
    drawNumber: 2,
    projectName: 'Johnson Beach House',
    milestone: 'Foundation Complete',
    amount: 180000,
    retainageAmount: 18000,
    netAmount: 162000,
    previousBilled: 120000,
    totalCompleted: 300000,
    percentComplete: 25,
    status: 'submitted',
    applicationDate: '2025-01-20',
    periodFrom: '2025-01-01',
    periodTo: '2025-01-31',
    description: 'Foundation, grade beams, and stem walls',
    formatType: 'custom',
    lenderName: 'Coastal Credit Union',
    submittedMethod: 'email',
    sovLineCount: 12,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 5, received: 5 }, photos: 10, inspections: { required: true, completed: true }, invoiceBackup: 7 },
    autoGenerated: false,
    storedMaterials: 0,
    contractAmount: 1200000,
  },
  {
    id: '7',
    drawNumber: 1,
    projectName: 'Miller Addition',
    milestone: 'Demolition & Framing',
    amount: 85000,
    retainageAmount: 8500,
    netAmount: 76500,
    previousBilled: 0,
    totalCompleted: 85000,
    percentComplete: 30,
    status: 'revision_requested',
    applicationDate: '2025-01-15',
    periodFrom: '2025-01-01',
    periodTo: '2025-01-31',
    description: 'Demo of existing structure and new framing',
    aiNote: 'Lender disputed 2 line items. Framing claimed 80% but inspector found 65%. Revision needed.',
    formatType: 'aia_g702',
    lenderName: 'First National Bank',
    submittedMethod: 'portal',
    approvedAmount: 72000,
    variance: -13000,
    revisionNumber: 1,
    sovLineCount: 10,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 3, received: 3 }, photos: 12, inspections: { required: true, completed: true }, invoiceBackup: 5 },
    autoGenerated: false,
    storedMaterials: 0,
    contractAmount: 285000,
  },
]

const statusConfig: Record<DrawStatus, { label: string; color: string; icon: typeof Calendar }> = {
  draft: { label: 'Draft', color: 'bg-warm-100 text-warm-700', icon: FileText },
  internal_review: { label: 'Internal Review', color: 'bg-stone-100 text-stone-700', icon: Eye },
  approved_internal: { label: 'Approved (Internal)', color: 'bg-stone-100 text-stone-700', icon: CheckCircle2 },
  submitted: { label: 'Submitted', color: 'bg-stone-100 text-stone-700', icon: Send },
  lender_review: { label: 'Lender Review', color: 'bg-amber-100 text-amber-700', icon: Clock },
  revision_requested: { label: 'Revision Requested', color: 'bg-red-100 text-red-700', icon: RotateCcw },
  approved: { label: 'Approved', color: 'bg-green-100 text-green-700', icon: CheckCircle2 },
  disbursed: { label: 'Disbursed', color: 'bg-emerald-100 text-emerald-700', icon: DollarSign },
  paid: { label: 'Paid', color: 'bg-green-100 text-green-700', icon: DollarSign },
}

function formatCurrency(value: number): string {
  const absValue = Math.abs(value)
  const sign = value < 0 ? '-' : ''
  if (absValue >= 1000000) return sign + '$' + (absValue / 1000000).toFixed(2) + 'M'
  if (absValue >= 1000) return sign + '$' + (absValue / 1000).toFixed(0) + 'K'
  return sign + '$' + absValue.toFixed(0)
}

function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function formatShortDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
}

function DocsChecklist({ docs }: { docs: DrawSupportingDocs }) {
  return (
    <div className="flex items-center gap-3 text-xs mt-1">
      <span className={cn(
        "flex items-center gap-1",
        docs.lienWaivers.received >= docs.lienWaivers.required ? "text-green-600" : "text-amber-600"
      )}>
        <FileCheck className="h-3 w-3" />
        Waivers: {docs.lienWaivers.received}/{docs.lienWaivers.required}
      </span>
      <span className="flex items-center gap-1 text-warm-500">
        <Camera className="h-3 w-3" />
        {docs.photos} photos
      </span>
      {docs.inspections.required ? <span className={cn(
          "flex items-center gap-1",
          docs.inspections.completed ? "text-green-600" : "text-amber-600"
        )}>
          <CheckCircle2 className="h-3 w-3" />
          Inspection: {docs.inspections.completed ? 'Passed' : 'Pending'}
        </span> : null}
      <span className="flex items-center gap-1 text-warm-500">
        <FileText className="h-3 w-3" />
        {docs.invoiceBackup} invoices
      </span>
    </div>
  )
}

function DrawRow({ draw, expanded, onToggle }: { draw: Draw; expanded: boolean; onToggle: () => void }) {
  const StatusIcon = statusConfig[draw.status].icon

  return (
    <>
      <tr
        className={cn(
          "hover:bg-warm-50 cursor-pointer",
          expanded && "bg-stone-50"
        )}
        onClick={onToggle}
      >
        <td className="py-3 px-4">
          <div className="flex items-center gap-2">
            {expanded ? (
              <ChevronDown className="h-4 w-4 text-warm-400" />
            ) : (
              <ChevronRight className="h-4 w-4 text-warm-400" />
            )}
            <span className="font-mono text-warm-500">#{draw.drawNumber}{draw.revisionNumber ? ` Rev ${String.fromCharCode(64 + draw.revisionNumber)}` : ''}</span>
            <span className="font-medium text-warm-900">{draw.milestone}</span>
            {draw.aiNote ? <Sparkles className="h-4 w-4 text-amber-500" /> : null}
            {draw.autoGenerated ? <span className="text-xs bg-warm-50 text-stone-600 px-1.5 py-0.5 rounded">Auto</span> : null}
          </div>
        </td>
        <td className="py-3 px-3 text-sm text-warm-600">
          <div className="flex items-center gap-1">
            <Building2 className="h-3.5 w-3.5 text-warm-400" />
            {draw.projectName}
          </div>
        </td>
        <td className="py-3 px-3 text-right font-medium text-warm-900">{formatCurrency(draw.amount)}</td>
        <td className="py-3 px-3 text-right text-warm-500 text-sm">{formatCurrency(draw.retainageAmount)}</td>
        <td className="py-3 px-3 text-center text-warm-600">{draw.percentComplete}%</td>
        <td className="py-3 px-3">
          <div className={cn(
            "inline-flex items-center gap-1.5 px-2 py-1 rounded text-xs font-medium",
            statusConfig[draw.status].color
          )}>
            <StatusIcon className="h-3.5 w-3.5" />
            {statusConfig[draw.status].label}
          </div>
        </td>
        <td className="py-3 px-3 text-warm-500 text-sm">{formatShortDate(draw.periodTo)}</td>
      </tr>
      {expanded ? <tr className="bg-stone-50">
          <td colSpan={7} className="py-3 px-12">
            <div className="space-y-2">
              {draw.description ? <div className="text-sm text-warm-600">
                  <span className="font-medium text-warm-700">Description:</span> {draw.description}
                </div> : null}
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div>
                  <span className="text-warm-500">Period:</span>{' '}
                  <span className="text-warm-700">{formatDate(draw.periodFrom)} - {formatDate(draw.periodTo)}</span>
                </div>
                <div>
                  <span className="text-warm-500">Net Amount:</span>{' '}
                  <span className="text-warm-700">{formatCurrency(draw.netAmount)}</span>
                </div>
                <div>
                  <span className="text-warm-500">Format:</span>{' '}
                  <span className="text-warm-700">{draw.formatType === 'aia_g702' ? 'AIA G702/G703' : draw.formatType === 'custom' ? 'Custom' : 'Lender Specific'}</span>
                </div>
                {draw.lenderName ? <div>
                    <span className="text-warm-500">Lender:</span>{' '}
                    <span className="text-warm-700">{draw.lenderName}</span>
                  </div> : null}
              </div>
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div>
                  <span className="text-warm-500">SOV Lines:</span>{' '}
                  <span className="text-warm-700">{draw.sovLineCount}</span>
                </div>
                {draw.changeOrdersIncluded > 0 && (
                  <div>
                    <span className="text-xs bg-sand-50 text-sand-600 px-1.5 py-0.5 rounded">
                      {draw.changeOrdersIncluded} CO{draw.changeOrdersIncluded !== 1 ? 's' : ''} included
                    </span>
                  </div>
                )}
                {draw.storedMaterials > 0 && (
                  <div>
                    <span className="text-warm-500">Stored Materials:</span>{' '}
                    <span className="text-warm-700">{formatCurrency(draw.storedMaterials)}</span>
                  </div>
                )}
                {draw.variance !== undefined && draw.variance !== 0 && (
                  <div>
                    <span className="text-warm-500">Variance:</span>{' '}
                    <span className={draw.variance < 0 ? "text-red-600 font-medium" : "text-green-600"}>
                      {formatCurrency(draw.variance)}
                    </span>
                  </div>
                )}
              </div>
              <DocsChecklist docs={draw.supportingDocs} />
              {draw.aiNote ? <div className="flex items-start gap-2 text-sm text-amber-700 mt-1">
                  <Sparkles className="h-4 w-4 mt-0.5 flex-shrink-0 text-amber-500" />
                  <span>{draw.aiNote}</span>
                </div> : null}
              <div className="flex gap-2 mt-2">
                {draw.status === 'draft' && (
                  <>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-stone-700 border border-stone-200 rounded-lg hover:bg-stone-50">
                      <Eye className="h-4 w-4" />
                      Submit for Review
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-warm-600 border border-warm-200 rounded-lg hover:bg-warm-50">
                      <FileText className="h-4 w-4" />
                      Preview G702
                    </button>
                  </>
                )}
                {(draw.status === 'approved_internal' || draw.status === 'internal_review') && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-stone-600 text-white rounded-lg hover:bg-stone-700">
                    <Send className="h-4 w-4" />
                    Submit to Lender
                  </button>
                )}
                {draw.status === 'approved' && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-green-600 text-white rounded-lg hover:bg-green-700">
                    <DollarSign className="h-4 w-4" />
                    Record Disbursement
                  </button>
                )}
                {draw.status === 'revision_requested' && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-amber-600 text-white rounded-lg hover:bg-amber-700">
                    <RotateCcw className="h-4 w-4" />
                    Create Revision
                  </button>
                )}
              </div>
            </div>
          </td>
        </tr> : null}
    </>
  )
}

function ProgressBar({ draws }: { draws: Draw[] }) {
  const totalAmount = draws.reduce((sum, d) => sum + d.amount, 0)

  const segments = draws.map(draw => ({
    ...draw,
    widthPercent: (draw.amount / totalAmount) * 100,
  }))

  const statusColors: Record<DrawStatus, string> = {
    paid: 'bg-green-500',
    disbursed: 'bg-emerald-500',
    approved: 'bg-amber-500',
    lender_review: 'bg-amber-400',
    submitted: 'bg-stone-500',
    approved_internal: 'bg-stone-400',
    internal_review: 'bg-stone-400',
    draft: 'bg-warm-300',
    revision_requested: 'bg-red-400',
  }

  return (
    <div className="space-y-2">
      <div className="flex h-4 rounded-full overflow-hidden bg-warm-200">
        {segments.map((segment) => (
          <div
            key={segment.id}
            className={cn("h-full transition-all", statusColors[segment.status])}
            style={{ width: `${segment.widthPercent}%` }}
            title={`Draw ${segment.drawNumber}: ${segment.milestone} - ${statusConfig[segment.status].label}`}
          />
        ))}
      </div>
      <div className="flex justify-between text-xs text-warm-500">
        <span>Contract Start</span>
        <span>Final Completion</span>
      </div>
    </div>
  )
}

export function DrawsPreview() {
  const { search, setSearch, activeTab, setActiveTab, activeSort, setActiveSort, sortDirection, toggleSortDirection } = useFilterState()
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set(['4']))
  const [projectFilter, setProjectFilter] = useState<string>('all')

  const projects = [...new Set(mockDraws.map(d => d.projectName))]

  const toggleRow = (id: string) => {
    setExpandedRows(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const filteredDraws = sortItems(
    mockDraws.filter(draw => {
      if (!matchesSearch(draw, search, ['milestone', 'description', 'projectName', 'lenderName'])) return false
      if (activeTab !== 'all' && draw.status !== activeTab) return false
      if (projectFilter !== 'all' && draw.projectName !== projectFilter) return false
      return true
    }),
    activeSort as keyof Draw | '',
    sortDirection,
  )

  const totalBilled = mockDraws.reduce((sum, d) => sum + d.amount, 0)
  const totalRetainage = mockDraws.reduce((sum, d) => sum + d.retainageAmount, 0)
  const totalDisbursed = mockDraws.filter(d => d.disbursedAmount).reduce((sum, d) => sum + (d.disbursedAmount || 0), 0)
  const pendingApproval = mockDraws.filter(d => ['submitted', 'lender_review', 'internal_review'].includes(d.status)).length
  const draftCount = mockDraws.filter(d => d.status === 'draft').length
  const revisionCount = mockDraws.filter(d => d.status === 'revision_requested').length
  const waiverIssues = mockDraws.filter(d => d.supportingDocs.lienWaivers.received < d.supportingDocs.lienWaivers.required).length

  return (
    <div className="bg-warm-50 rounded-lg border border-warm-200 overflow-hidden">
      {/* Header */}
      <div className="bg-white border-b border-warm-200 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3">
              <h3 className="font-semibold text-warm-900">Draw Requests</h3>
              <span className="text-sm text-warm-500">{mockDraws.length} draws across {projects.length} projects</span>
              {revisionCount > 0 && (
                <span className="text-xs px-2 py-0.5 rounded bg-red-100 text-red-700 font-medium flex items-center gap-1">
                  <RotateCcw className="h-3 w-3" />
                  {revisionCount} revision{revisionCount !== 1 ? 's' : ''} needed
                </span>
              )}
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-warm-600 border border-warm-200 rounded-lg hover:bg-warm-50">
              <Download className="h-4 w-4" />
              Export
            </button>
            <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-stone-600 text-white rounded-lg hover:bg-stone-700">
              <Plus className="h-4 w-4" />
              New Draw
            </button>
          </div>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="bg-white border-b border-warm-200 px-4 py-4">
        <div className="grid grid-cols-5 gap-3">
          <div className="bg-stone-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-stone-600 text-sm">
              <TrendingUp className="h-4 w-4" />
              Total Billed
            </div>
            <div className="text-xl font-bold text-warm-900 mt-1">{formatCurrency(totalBilled)}</div>
          </div>
          <div className="bg-warm-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-warm-500 text-sm">
              <DollarSign className="h-4 w-4" />
              Total Retainage
            </div>
            <div className="text-xl font-bold text-warm-700 mt-1">{formatCurrency(totalRetainage)}</div>
          </div>
          <div className="bg-green-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-green-600 text-sm">
              <DollarSign className="h-4 w-4" />
              Disbursed
            </div>
            <div className="text-xl font-bold text-green-700 mt-1">{formatCurrency(totalDisbursed)}</div>
          </div>
          <div className={cn("rounded-lg p-3", pendingApproval > 0 ? "bg-amber-50" : "bg-warm-50")}>
            <div className={cn("flex items-center gap-2 text-sm", pendingApproval > 0 ? "text-amber-600" : "text-warm-500")}>
              <Clock className="h-4 w-4" />
              Pending Approval
            </div>
            <div className={cn("text-xl font-bold mt-1", pendingApproval > 0 ? "text-amber-700" : "text-warm-500")}>
              {pendingApproval} draw{pendingApproval !== 1 ? 's' : ''}
            </div>
          </div>
          <div className={cn("rounded-lg p-3", waiverIssues > 0 ? "bg-red-50" : "bg-warm-50")}>
            <div className={cn("flex items-center gap-2 text-sm", waiverIssues > 0 ? "text-red-600" : "text-warm-500")}>
              <FileCheck className="h-4 w-4" />
              Waiver Issues
            </div>
            <div className={cn("text-xl font-bold mt-1", waiverIssues > 0 ? "text-red-700" : "text-warm-500")}>
              {waiverIssues} draw{waiverIssues !== 1 ? 's' : ''}
            </div>
          </div>
        </div>
      </div>

      {/* FilterBar */}
      <div className="bg-white border-b border-warm-200 px-4 py-3">
        <FilterBar
          search={search}
          onSearchChange={setSearch}
          searchPlaceholder="Search draws, projects, lenders..."
          tabs={[
            { key: 'all', label: 'All', count: mockDraws.length },
            { key: 'draft', label: 'Draft', count: mockDraws.filter(d => d.status === 'draft').length },
            { key: 'submitted', label: 'Submitted', count: mockDraws.filter(d => ['submitted', 'lender_review'].includes(d.status)).length },
            { key: 'revision_requested', label: 'Revision', count: mockDraws.filter(d => d.status === 'revision_requested').length },
            { key: 'approved', label: 'Approved', count: mockDraws.filter(d => d.status === 'approved').length },
            { key: 'paid', label: 'Paid', count: mockDraws.filter(d => ['paid', 'disbursed'].includes(d.status)).length },
          ]}
          activeTab={activeTab}
          onTabChange={setActiveTab}
          dropdowns={[
            {
              label: 'All Projects',
              value: projectFilter,
              options: projects.map(p => ({ value: p, label: p })),
              onChange: setProjectFilter,
            },
          ]}
          sortOptions={[
            { value: 'drawNumber', label: 'Draw #' },
            { value: 'amount', label: 'Amount' },
            { value: 'projectName', label: 'Project' },
            { value: 'applicationDate', label: 'Date' },
            { value: 'status', label: 'Status' },
            { value: 'percentComplete', label: '% Complete' },
          ]}
          activeSort={activeSort}
          onSortChange={setActiveSort}
          sortDirection={sortDirection}
          onSortDirectionChange={toggleSortDirection}
          resultCount={filteredDraws.length}
          totalCount={mockDraws.length}
        />
      </div>

      {/* Progress Bar (for single-project view) */}
      {projectFilter !== 'all' && (
        <div className="bg-white border-b border-warm-200 px-4 py-4">
          <div className="flex items-center gap-4 mb-3">
            <span className="text-sm font-medium text-warm-700">Draw Progress</span>
            <div className="flex items-center gap-3 text-xs text-warm-500">
              <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-green-500 rounded" /><span>Paid</span></div>
              <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-amber-500 rounded" /><span>Approved</span></div>
              <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-stone-500 rounded" /><span>Submitted</span></div>
              <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-warm-300 rounded" /><span>Draft</span></div>
              <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-red-400 rounded" /><span>Revision</span></div>
            </div>
          </div>
          <ProgressBar draws={filteredDraws} />
        </div>
      )}

      {/* Draw Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-warm-100 border-b border-warm-200">
            <tr>
              <th className="text-left py-3 px-4 font-medium text-warm-600">Draw / Milestone</th>
              <th className="text-left py-3 px-3 font-medium text-warm-600">Project</th>
              <th className="text-right py-3 px-3 font-medium text-warm-600">Amount</th>
              <th className="text-right py-3 px-3 font-medium text-warm-600">Retainage</th>
              <th className="text-center py-3 px-3 font-medium text-warm-600">% Complete</th>
              <th className="text-left py-3 px-3 font-medium text-warm-600">Status</th>
              <th className="text-left py-3 px-3 font-medium text-warm-600">Period</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-warm-100">
            {filteredDraws.map(draw => (
              <DrawRow
                key={draw.id}
                draw={draw}
                expanded={expandedRows.has(draw.id)}
                onToggle={() => toggleRow(draw.id)}
              />
            ))}
          </tbody>
        </table>
      </div>

      {/* AI Insights Bar */}
      <div className="bg-warm-50 border-t border-amber-200 px-4 py-3">
        <div className="flex items-start gap-3">
          <div className="flex items-center gap-2 flex-shrink-0">
            <Sparkles className="h-4 w-4 text-amber-600" />
            <span className="font-medium text-sm text-amber-800">Draw Intelligence:</span>
          </div>
          <p className="text-sm text-amber-700">
            Draw #4 (Smith) pending bank inspection - typically 3-5 business days. Miller Addition Draw #1 Rev A needed -
            lender adjusted framing from 80% to 65%. 2 draws have incomplete lien waiver packages.
            Based on 23 similar projects, submit Draw #5 documentation 5 days before milestone for 40% faster approval.
          </p>
        </div>
      </div>

      {/* AI Features Panel */}
      <div className="bg-white border-t border-warm-200 px-4 py-4">
        <AIFeaturesPanel
          title="AI-Powered Draw Management"
          columns={2}
          features={[
            {
              feature: 'Completion Verification',
              trigger: 'on-submission',
              insight: 'Validates work completion before draw submission by cross-referencing progress photos, inspection reports, and subcontractor sign-offs.',
              severity: 'info',
              confidence: 94,
            },
            {
              feature: 'Overbilling Detection',
              trigger: 'real-time',
              insight: 'Flags potential overbilling by comparing claimed percentages against historical patterns and industry benchmarks.',
              severity: 'warning',
              confidence: 87,
            },
            {
              feature: 'Draw Timing Optimization',
              trigger: 'daily',
              insight: 'Suggests optimal draw timing based on lender processing patterns, cash flow needs, and project milestones.',
              severity: 'success',
              confidence: 91,
            },
            {
              feature: 'Lender Pattern Analysis',
              trigger: 'on-change',
              insight: 'Tracks lender approval patterns including average review times, common revision requests, and inspector preferences.',
              severity: 'info',
              confidence: 88,
            },
            {
              feature: 'Cash Flow Projection',
              trigger: 'real-time',
              insight: 'Projects cash flow impact of pending draws, accounting for retainage schedules and typical disbursement timelines.',
              severity: 'info',
              confidence: 92,
            },
          ]}
        />
      </div>
    </div>
  )
}
