'use client'

import { useState } from 'react'
import {
  ChevronDown,
  ChevronRight,
  Download,
  Plus,
  Send,
  CheckCircle2,
  Clock,
  DollarSign,
  FileText,
  Calendar,
  TrendingUp,
  Percent,
  FileCheck,
  AlertTriangle,
  Eye,
  Camera,
  RotateCcw,
  Layers,
  ClipboardList,
  ArrowRightLeft,
  Package,
  MapPin,
  Shield,
  BookOpen,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { FilterBar } from '@/components/skeleton/filter-bar'
import { useFilterState, matchesSearch, sortItems } from '@/hooks/use-filter-state'
import { AIFeatureCard, AIFeaturesPanel } from '@/components/skeleton/ui'

type DrawStatus = 'draft' | 'internal_review' | 'submitted' | 'lender_review' | 'revision_requested' | 'approved' | 'disbursed'

interface SOVLineSummary {
  lineNumber: string
  description: string
  scheduledValue: number
  previousCompleted: number
  currentCompleted: number
  storedMaterials: number
  percentComplete: number
}

interface StoredMaterialItem {
  description: string
  amount: number
  location: string
  verified: boolean
  verificationDate?: string
}

interface DrawSupportingDocs {
  lienWaivers: { required: number; received: number }
  photos: number
  inspections: { required: boolean; completed: boolean }
  invoiceBackup: number
}

interface Draw {
  id: string
  drawNumber: number
  milestone: string
  amount: number
  retainageAmount: number
  retainagePercent: number
  netAmount: number
  previousBilled: number
  totalCompleted: number
  percentComplete: number
  status: DrawStatus
  applicationDate: string
  periodFrom: string
  periodTo: string
  description?: string
  aiNote?: string
  formatType: 'aia_g702' | 'custom' | 'lender_specific'
  lenderName: string
  submittedMethod?: 'portal' | 'email' | 'physical'
  approvedAmount?: number
  disbursedAmount?: number
  variance?: number
  sovLineCount: number
  changeOrdersIncluded: number
  supportingDocs: DrawSupportingDocs
  revisionNumber?: number
  autoGenerated: boolean
  storedMaterials: number
  storedMaterialItems?: StoredMaterialItem[]
  includedInvoices: number
  sovLines?: SOVLineSummary[]
  dailyLogsCount?: number
}

const contractAmount = 2510000
const originalContractAmount = 2450000
const netChangeOrders = 60000
const lenderName = 'First National Bank'

const mockDraws: Draw[] = [
  {
    id: '1',
    drawNumber: 1,
    milestone: 'Contract Signing',
    amount: 245000,
    retainageAmount: 24500,
    retainagePercent: 10,
    netAmount: 220500,
    previousBilled: 0,
    totalCompleted: 245000,
    percentComplete: 10,
    status: 'disbursed',
    applicationDate: '2024-10-15',
    periodFrom: '2024-10-01',
    periodTo: '2024-10-31',
    description: 'Initial deposit upon contract execution',
    formatType: 'aia_g702',
    lenderName,
    submittedMethod: 'portal',
    approvedAmount: 245000,
    disbursedAmount: 220500,
    sovLineCount: 15,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 0, received: 0 }, photos: 0, inspections: { required: false, completed: false }, invoiceBackup: 0 },
    autoGenerated: false,
    storedMaterials: 0,
    includedInvoices: 0,
  },
  {
    id: '2',
    drawNumber: 2,
    milestone: 'Foundation Complete',
    amount: 367500,
    retainageAmount: 36750,
    retainagePercent: 10,
    netAmount: 330750,
    previousBilled: 245000,
    totalCompleted: 612500,
    percentComplete: 25,
    status: 'disbursed',
    applicationDate: '2024-11-08',
    periodFrom: '2024-11-01',
    periodTo: '2024-11-30',
    description: 'Pilings, grade beams, and slab complete',
    formatType: 'aia_g702',
    lenderName,
    submittedMethod: 'portal',
    approvedAmount: 367500,
    disbursedAmount: 330750,
    sovLineCount: 15,
    changeOrdersIncluded: 0,
    supportingDocs: { lienWaivers: { required: 4, received: 4 }, photos: 8, inspections: { required: true, completed: true }, invoiceBackup: 6 },
    autoGenerated: false,
    storedMaterials: 0,
    includedInvoices: 6,
    dailyLogsCount: 12,
  },
  {
    id: '3',
    drawNumber: 3,
    milestone: 'Framing Complete',
    amount: 490000,
    retainageAmount: 49000,
    retainagePercent: 10,
    netAmount: 441000,
    previousBilled: 612500,
    totalCompleted: 1102500,
    percentComplete: 45,
    status: 'approved',
    applicationDate: '2024-12-12',
    periodFrom: '2024-12-01',
    periodTo: '2024-12-31',
    description: 'Structural framing and roof sheathing',
    aiNote: 'Approved 2 days faster than average. Lender inspection passed.',
    formatType: 'aia_g702',
    lenderName,
    submittedMethod: 'email',
    approvedAmount: 490000,
    sovLineCount: 18,
    changeOrdersIncluded: 1,
    supportingDocs: { lienWaivers: { required: 7, received: 7 }, photos: 15, inspections: { required: true, completed: true }, invoiceBackup: 12 },
    autoGenerated: false,
    storedMaterials: 18500,
    storedMaterialItems: [
      { description: 'Window units (6 of 12)', amount: 12500, location: 'On-site secured storage', verified: true, verificationDate: '2024-12-10' },
      { description: 'Exterior door hardware', amount: 6000, location: 'Supplier warehouse - ABC Supply', verified: true, verificationDate: '2024-12-08' },
    ],
    includedInvoices: 12,
    dailyLogsCount: 18,
  },
  {
    id: '4',
    drawNumber: 4,
    milestone: 'Dried In',
    amount: 367500,
    retainageAmount: 36750,
    retainagePercent: 10,
    netAmount: 330750,
    previousBilled: 1102500,
    totalCompleted: 1470000,
    percentComplete: 60,
    status: 'lender_review',
    applicationDate: '2025-01-05',
    periodFrom: '2025-01-01',
    periodTo: '2025-01-31',
    description: 'Windows, doors, and roofing installed',
    aiNote: 'Pending bank inspection - inspector Tom Williams scheduled Jan 10. Typically 3-5 day review after inspection.',
    formatType: 'aia_g702',
    lenderName,
    submittedMethod: 'portal',
    sovLineCount: 18,
    changeOrdersIncluded: 1,
    supportingDocs: { lienWaivers: { required: 8, received: 6 }, photos: 18, inspections: { required: true, completed: false }, invoiceBackup: 14 },
    autoGenerated: true,
    storedMaterials: 22000,
    storedMaterialItems: [
      { description: 'HVAC equipment - 2 units', amount: 14000, location: 'On-site garage bay', verified: true, verificationDate: '2025-01-03' },
      { description: 'Plumbing fixtures lot', amount: 5000, location: 'On-site secured storage', verified: true, verificationDate: '2025-01-02' },
      { description: 'Electrical panel & breakers', amount: 3000, location: 'Distributor warehouse - Electric Plus', verified: false },
    ],
    includedInvoices: 14,
    dailyLogsCount: 22,
    sovLines: [
      { lineNumber: '01', description: 'General Conditions', scheduledValue: 125000, previousCompleted: 62500, currentCompleted: 12500, storedMaterials: 0, percentComplete: 60 },
      { lineNumber: '03', description: 'Concrete / Foundation', scheduledValue: 185000, previousCompleted: 185000, currentCompleted: 0, storedMaterials: 0, percentComplete: 100 },
      { lineNumber: '06', description: 'Framing & Lumber', scheduledValue: 320000, previousCompleted: 288000, currentCompleted: 32000, storedMaterials: 0, percentComplete: 100 },
      { lineNumber: '07', description: 'Roofing', scheduledValue: 95000, previousCompleted: 0, currentCompleted: 85500, storedMaterials: 0, percentComplete: 90 },
      { lineNumber: '08', description: 'Windows & Doors', scheduledValue: 210000, previousCompleted: 0, currentCompleted: 189000, storedMaterials: 22000, percentComplete: 90 },
    ],
  },
  {
    id: '5',
    drawNumber: 5,
    milestone: 'MEP Rough Complete',
    amount: 367500,
    retainageAmount: 36750,
    retainagePercent: 10,
    netAmount: 330750,
    previousBilled: 1470000,
    totalCompleted: 1837500,
    percentComplete: 75,
    status: 'internal_review',
    applicationDate: '2025-02-01',
    periodFrom: '2025-02-01',
    periodTo: '2025-02-28',
    description: 'Electrical, plumbing, and HVAC rough-in',
    aiNote: 'Auto-generated from approved invoices and schedule progress. 3 SOV lines need manual review.',
    formatType: 'aia_g702',
    lenderName,
    sovLineCount: 18,
    changeOrdersIncluded: 2,
    supportingDocs: { lienWaivers: { required: 9, received: 3 }, photos: 6, inspections: { required: true, completed: false }, invoiceBackup: 8 },
    autoGenerated: true,
    storedMaterials: 15000,
    storedMaterialItems: [
      { description: 'Drywall sheets - 200 units', amount: 8000, location: 'On-site interior stack', verified: true, verificationDate: '2025-01-28' },
      { description: 'Insulation batts - R-30', amount: 4500, location: 'On-site garage bay', verified: true, verificationDate: '2025-01-28' },
      { description: 'Trim package - Phase 1', amount: 2500, location: 'Supplier holding - Premium Lumber', verified: false },
    ],
    includedInvoices: 8,
    dailyLogsCount: 15,
  },
  {
    id: '6',
    drawNumber: 6,
    milestone: 'Drywall Complete',
    amount: 245000,
    retainageAmount: 12250,
    retainagePercent: 5,
    netAmount: 232750,
    previousBilled: 1837500,
    totalCompleted: 2082500,
    percentComplete: 85,
    status: 'draft',
    applicationDate: '2025-03-01',
    periodFrom: '2025-03-01',
    periodTo: '2025-03-31',
    description: 'Drywall hung, taped, and finished. Retainage reduced to 5% at 50% completion.',
    formatType: 'aia_g702',
    lenderName,
    sovLineCount: 18,
    changeOrdersIncluded: 2,
    supportingDocs: { lienWaivers: { required: 0, received: 0 }, photos: 0, inspections: { required: false, completed: false }, invoiceBackup: 0 },
    autoGenerated: false,
    storedMaterials: 0,
    includedInvoices: 0,
  },
  {
    id: '7',
    drawNumber: 7,
    milestone: 'Final Completion',
    amount: 367500,
    retainageAmount: 18375,
    retainagePercent: 5,
    netAmount: 349125,
    previousBilled: 2082500,
    totalCompleted: 2450000,
    percentComplete: 100,
    status: 'draft',
    applicationDate: '2025-04-15',
    periodFrom: '2025-04-01',
    periodTo: '2025-04-30',
    description: 'Certificate of occupancy and final walkthrough. Final retainage release.',
    formatType: 'aia_g702',
    lenderName,
    sovLineCount: 18,
    changeOrdersIncluded: 2,
    supportingDocs: { lienWaivers: { required: 0, received: 0 }, photos: 0, inspections: { required: false, completed: false }, invoiceBackup: 0 },
    autoGenerated: false,
    storedMaterials: 0,
    includedInvoices: 0,
  },
]

const statusConfig: Record<DrawStatus, { label: string; color: string; icon: typeof Calendar }> = {
  draft: { label: 'Draft', color: 'bg-gray-100 text-gray-700', icon: FileText },
  internal_review: { label: 'Internal Review', color: 'bg-indigo-100 text-indigo-700', icon: Eye },
  submitted: { label: 'Submitted', color: 'bg-blue-100 text-blue-700', icon: Send },
  lender_review: { label: 'Lender Review', color: 'bg-amber-100 text-amber-700', icon: Clock },
  revision_requested: { label: 'Revision Requested', color: 'bg-red-100 text-red-700', icon: RotateCcw },
  approved: { label: 'Approved', color: 'bg-green-100 text-green-700', icon: CheckCircle2 },
  disbursed: { label: 'Disbursed', color: 'bg-emerald-100 text-emerald-700', icon: DollarSign },
}

function formatCurrency(value: number): string {
  const absValue = Math.abs(value)
  const sign = value < 0 ? '-' : ''
  if (absValue >= 1000000) return sign + '$' + (absValue / 1000000).toFixed(2) + 'M'
  if (absValue >= 1000) return sign + '$' + (absValue / 1000).toFixed(0) + 'K'
  return sign + '$' + absValue.toFixed(0)
}

function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function formatShortDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
}

function DocsChecklist({ docs }: { docs: DrawSupportingDocs }) {
  return (
    <div className="flex items-center gap-3 text-xs mt-1">
      <span className={cn(
        "flex items-center gap-1",
        docs.lienWaivers.required === 0 ? "text-gray-400" :
        docs.lienWaivers.received >= docs.lienWaivers.required ? "text-green-600" : "text-amber-600"
      )}>
        <FileCheck className="h-3 w-3" />
        Waivers: {docs.lienWaivers.received}/{docs.lienWaivers.required}
      </span>
      <span className="flex items-center gap-1 text-gray-500">
        <Camera className="h-3 w-3" />
        {docs.photos} photos
      </span>
      {docs.inspections.required && (
        <span className={cn(
          "flex items-center gap-1",
          docs.inspections.completed ? "text-green-600" : "text-amber-600"
        )}>
          <CheckCircle2 className="h-3 w-3" />
          Inspection: {docs.inspections.completed ? 'Passed' : 'Pending'}
        </span>
      )}
      <span className="flex items-center gap-1 text-gray-500">
        <ClipboardList className="h-3 w-3" />
        {docs.invoiceBackup} invoices
      </span>
    </div>
  )
}

function StoredMaterialsBreakdown({ items }: { items: StoredMaterialItem[] }) {
  return (
    <div className="mt-2">
      <div className="text-xs font-medium text-gray-600 mb-1 flex items-center gap-1">
        <Package className="h-3 w-3" />
        Stored Materials Breakdown:
      </div>
      <div className="bg-white rounded border border-gray-200 overflow-hidden">
        <table className="w-full text-xs">
          <thead className="bg-gray-50">
            <tr>
              <th className="text-left py-1.5 px-2 text-gray-500">Description</th>
              <th className="text-right py-1.5 px-2 text-gray-500">Amount</th>
              <th className="text-left py-1.5 px-2 text-gray-500">Location</th>
              <th className="text-center py-1.5 px-2 text-gray-500">Verified</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {items.map((item, i) => (
              <tr key={i}>
                <td className="py-1.5 px-2 text-gray-700">{item.description}</td>
                <td className="py-1.5 px-2 text-right text-gray-700 font-medium">{formatCurrency(item.amount)}</td>
                <td className="py-1.5 px-2 text-gray-600">
                  <span className="flex items-center gap-1">
                    <MapPin className="h-3 w-3 text-gray-400" />
                    {item.location}
                  </span>
                </td>
                <td className="py-1.5 px-2 text-center">
                  {item.verified ? (
                    <span className="inline-flex items-center gap-1 text-green-600">
                      <Shield className="h-3 w-3" />
                      {item.verificationDate && <span className="text-gray-400">{item.verificationDate}</span>}
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-amber-600">
                      <AlertTriangle className="h-3 w-3" />
                      Pending
                    </span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

function DrawRow({ draw, expanded, onToggle }: { draw: Draw; expanded: boolean; onToggle: () => void }) {
  const StatusIcon = statusConfig[draw.status].icon

  return (
    <>
      <tr
        className={cn(
          "hover:bg-gray-50 cursor-pointer",
          expanded && "bg-blue-50"
        )}
        onClick={onToggle}
      >
        <td className="py-3 px-4">
          <div className="flex items-center gap-2">
            {expanded ? (
              <ChevronDown className="h-4 w-4 text-gray-400" />
            ) : (
              <ChevronRight className="h-4 w-4 text-gray-400" />
            )}
            <span className="font-mono text-gray-500">#{draw.drawNumber}{draw.revisionNumber ? ` Rev ${String.fromCharCode(64 + draw.revisionNumber)}` : ''}</span>
            <span className="font-medium text-gray-900">{draw.milestone}</span>
            {draw.autoGenerated && <span className="text-xs bg-purple-50 text-purple-600 px-1.5 py-0.5 rounded">Auto</span>}
            {draw.changeOrdersIncluded > 0 && (
              <span className="text-xs bg-orange-50 text-orange-600 px-1.5 py-0.5 rounded">
                +{draw.changeOrdersIncluded} CO
              </span>
            )}
            {draw.dailyLogsCount && draw.dailyLogsCount > 0 && (
              <span className="text-xs bg-cyan-50 text-cyan-600 px-1.5 py-0.5 rounded flex items-center gap-1">
                <BookOpen className="h-3 w-3" />
                {draw.dailyLogsCount} logs
              </span>
            )}
          </div>
        </td>
        <td className="py-3 px-3 text-right font-medium text-gray-900">{formatCurrency(draw.amount)}</td>
        <td className="py-3 px-3 text-right text-gray-500 text-sm">{formatCurrency(draw.retainageAmount)} ({draw.retainagePercent}%)</td>
        <td className="py-3 px-3 text-right text-gray-600">{formatCurrency(draw.netAmount)}</td>
        <td className="py-3 px-3 text-center text-gray-600">{draw.percentComplete}%</td>
        <td className="py-3 px-3">
          <div className={cn(
            "inline-flex items-center gap-1.5 px-2 py-1 rounded text-xs font-medium",
            statusConfig[draw.status].color
          )}>
            <StatusIcon className="h-3.5 w-3.5" />
            {statusConfig[draw.status].label}
          </div>
        </td>
        <td className="py-3 px-3 text-gray-500 text-sm">{formatShortDate(draw.periodTo)}</td>
      </tr>
      {expanded && (
        <tr className="bg-blue-50">
          <td colSpan={7} className="py-3 px-12">
            <div className="space-y-3">
              {draw.description && (
                <div className="text-sm text-gray-600">
                  <span className="font-medium text-gray-700">Description:</span> {draw.description}
                </div>
              )}
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div><span className="text-gray-500">Period:</span> <span className="text-gray-700">{formatDate(draw.periodFrom)} - {formatDate(draw.periodTo)}</span></div>
                <div><span className="text-gray-500">Format:</span> <span className="text-gray-700">{draw.formatType === 'aia_g702' ? 'AIA G702/G703' : 'Custom'}</span></div>
                <div><span className="text-gray-500">Lender:</span> <span className="text-gray-700">{draw.lenderName}</span></div>
                {draw.storedMaterials > 0 && (
                  <div><span className="text-gray-500">Stored Materials:</span> <span className="text-gray-700">{formatCurrency(draw.storedMaterials)}</span></div>
                )}
              </div>
              <div className="grid grid-cols-4 gap-4 text-sm">
                <div><span className="text-gray-500">SOV Lines:</span> <span className="text-gray-700">{draw.sovLineCount}</span></div>
                <div><span className="text-gray-500">Included Invoices:</span> <span className="text-gray-700">{draw.includedInvoices}</span></div>
                {draw.dailyLogsCount && draw.dailyLogsCount > 0 && (
                  <div className="flex items-center gap-1">
                    <BookOpen className="h-3.5 w-3.5 text-cyan-600" />
                    <span className="text-cyan-700 font-medium">Supported by {draw.dailyLogsCount} daily log entries</span>
                  </div>
                )}
                {draw.variance !== undefined && draw.variance !== 0 && (
                  <div><span className="text-gray-500">Variance:</span> <span className={draw.variance < 0 ? "text-red-600 font-medium" : "text-green-600"}>{formatCurrency(draw.variance)}</span></div>
                )}
              </div>
              <DocsChecklist docs={draw.supportingDocs} />

              {/* Stored Materials Breakdown */}
              {draw.storedMaterialItems && draw.storedMaterialItems.length > 0 && (
                <StoredMaterialsBreakdown items={draw.storedMaterialItems} />
              )}

              {/* SOV Line Preview for expanded draws */}
              {draw.sovLines && draw.sovLines.length > 0 && (
                <div className="mt-2">
                  <div className="text-xs font-medium text-gray-600 mb-1">SOV Summary (Top Lines):</div>
                  <div className="bg-white rounded border border-gray-200 overflow-hidden">
                    <table className="w-full text-xs">
                      <thead className="bg-gray-50">
                        <tr>
                          <th className="text-left py-1.5 px-2 text-gray-500">Line</th>
                          <th className="text-left py-1.5 px-2 text-gray-500">Description</th>
                          <th className="text-right py-1.5 px-2 text-gray-500">Scheduled</th>
                          <th className="text-right py-1.5 px-2 text-gray-500">This Period</th>
                          <th className="text-center py-1.5 px-2 text-gray-500">%</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {draw.sovLines.map((line, i) => (
                          <tr key={i}>
                            <td className="py-1.5 px-2 font-mono text-gray-600">{line.lineNumber}</td>
                            <td className="py-1.5 px-2 text-gray-700">{line.description}</td>
                            <td className="py-1.5 px-2 text-right text-gray-600">{formatCurrency(line.scheduledValue)}</td>
                            <td className="py-1.5 px-2 text-right text-gray-700 font-medium">{formatCurrency(line.currentCompleted)}</td>
                            <td className="py-1.5 px-2 text-center text-gray-600">{line.percentComplete}%</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {draw.aiNote && (
                <div className="flex items-start gap-2 text-sm text-amber-700 bg-amber-50 rounded-lg p-2 border border-amber-200">
                  <AlertTriangle className="h-4 w-4 mt-0.5 flex-shrink-0 text-amber-500" />
                  <span>{draw.aiNote}</span>
                </div>
              )}
              <div className="flex gap-2 mt-2">
                {draw.status === 'draft' && (
                  <>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-indigo-700 border border-indigo-200 rounded-lg hover:bg-indigo-50">
                      <Eye className="h-4 w-4" />
                      Submit for Review
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50">
                      <FileText className="h-4 w-4" />
                      Preview G702
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50">
                      <Layers className="h-4 w-4" />
                      Assemble Docs
                    </button>
                  </>
                )}
                {draw.status === 'internal_review' && (
                  <>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                      <Send className="h-4 w-4" />
                      Submit to Lender
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50">
                      <RotateCcw className="h-4 w-4" />
                      Request Revisions
                    </button>
                  </>
                )}
                {draw.status === 'approved' && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-green-600 text-white rounded-lg hover:bg-green-700">
                    <DollarSign className="h-4 w-4" />
                    Record Disbursement
                  </button>
                )}
                {draw.status === 'lender_review' && (
                  <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50">
                    <ArrowRightLeft className="h-4 w-4" />
                    Record Lender Response
                  </button>
                )}
              </div>
            </div>
          </td>
        </tr>
      )}
    </>
  )
}

function ProgressBar({ draws }: { draws: Draw[] }) {
  const totalAmount = draws.reduce((sum, d) => sum + d.amount, 0)

  const segments = draws.map(draw => ({
    ...draw,
    widthPercent: (draw.amount / totalAmount) * 100,
  }))

  const statusColors: Record<DrawStatus, string> = {
    disbursed: 'bg-green-500',
    approved: 'bg-amber-500',
    lender_review: 'bg-yellow-400',
    submitted: 'bg-blue-500',
    internal_review: 'bg-indigo-400',
    draft: 'bg-gray-300',
    revision_requested: 'bg-red-400',
  }

  return (
    <div className="space-y-2">
      <div className="flex h-4 rounded-full overflow-hidden bg-gray-200">
        {segments.map((segment) => (
          <div
            key={segment.id}
            className={cn("h-full transition-all", statusColors[segment.status])}
            style={{ width: `${segment.widthPercent}%` }}
            title={`Draw ${segment.drawNumber}: ${segment.milestone} - ${statusConfig[segment.status].label}`}
          />
        ))}
      </div>
      <div className="flex justify-between text-xs text-gray-500">
        <span>Contract Start</span>
        <span>Final Completion</span>
      </div>
    </div>
  )
}

// AI Features for Draw Intelligence
const drawAIFeatures = [
  {
    feature: 'Completion Verification',
    trigger: 'On submission',
    insight: 'Cross-referenced: Schedule shows framing 95% complete, daily logs confirm. 3 photos from Feb 10 support claim.',
    severity: 'success' as const,
    confidence: 94,
  },
  {
    feature: 'Overbilling Detection',
    trigger: 'Real-time',
    insight: 'Warning: Claiming 90% on 05-Roofing but schedule shows 75%. Review before submission.',
    severity: 'warning' as const,
    confidence: 87,
  },
  {
    feature: 'Draw Timing Optimization',
    trigger: 'Daily',
    insight: 'Optimal submission window: Feb 15-18. Lender typically processes in 5 days, funding by Feb 23.',
    severity: 'info' as const,
    confidence: 82,
  },
  {
    feature: 'Lender Pattern Analysis',
    trigger: 'Weekly',
    insight: 'First National avg response: 4.2 days. Last 3 draws approved without revision. Good track record.',
    severity: 'success' as const,
    confidence: 91,
  },
]

export function JobDrawsPreview() {
  const { search, setSearch, activeTab, setActiveTab, activeSort, setActiveSort, sortDirection, toggleSortDirection } = useFilterState()
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set(['4']))

  const toggleRow = (id: string) => {
    setExpandedRows(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  const disbursedDraws = mockDraws.filter(d => d.status === 'disbursed')
  const amountBilled = mockDraws
    .filter(d => !['draft'].includes(d.status))
    .reduce((sum, d) => sum + d.amount, 0)
  const amountPaid = disbursedDraws.reduce((sum, d) => sum + (d.disbursedAmount || 0), 0)
  const totalRetainage = mockDraws
    .filter(d => !['draft'].includes(d.status))
    .reduce((sum, d) => sum + d.retainageAmount, 0)
  const amountRemaining = contractAmount - amountBilled
  const percentComplete = Math.round((amountBilled / contractAmount) * 100)

  const filteredDraws = sortItems(
    mockDraws.filter(draw => {
      if (!matchesSearch(draw, search, ['milestone', 'description'])) return false
      if (activeTab !== 'all' && draw.status !== activeTab) return false
      return true
    }),
    activeSort as keyof Draw | '',
    sortDirection,
  )

  return (
    <div className="bg-gray-50 rounded-lg border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-4 py-3">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3">
              <h3 className="font-semibold text-gray-900">Draw Schedule - Smith Residence</h3>
              <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">In Progress</span>
            </div>
            <div className="text-sm text-gray-500 mt-0.5 flex items-center gap-4">
              <span className="flex items-center gap-1">
                <FileText className="h-4 w-4" />
                Contract: {formatCurrency(contractAmount)}
                {netChangeOrders > 0 && (
                  <span className="text-xs bg-orange-50 text-orange-600 px-1.5 py-0.5 rounded ml-1">
                    +{formatCurrency(netChangeOrders)} COs
                  </span>
                )}
              </span>
              <span className="flex items-center gap-1">
                <Clock className="h-4 w-4" />
                {mockDraws.length} Draws
              </span>
              <span className="flex items-center gap-1 text-gray-400">
                Lender: {lenderName}
              </span>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50">
              <Download className="h-4 w-4" />
              Export
            </button>
            <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700">
              <Plus className="h-4 w-4" />
              Add Draw
            </button>
          </div>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="bg-white border-b border-gray-200 px-4 py-4">
        <div className="grid grid-cols-5 gap-3">
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-gray-500 text-sm">
              <CheckCircle2 className="h-4 w-4" />
              Draws Completed
            </div>
            <div className="text-xl font-bold text-gray-900 mt-1">
              {disbursedDraws.length} of {mockDraws.length}
            </div>
          </div>
          <div className="bg-blue-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-blue-600 text-sm">
              <TrendingUp className="h-4 w-4" />
              Amount Billed
            </div>
            <div className="text-xl font-bold text-gray-900 mt-1">{formatCurrency(amountBilled)}</div>
          </div>
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-gray-500 text-sm">
              <DollarSign className="h-4 w-4" />
              Retainage Held
            </div>
            <div className="text-xl font-bold text-gray-700 mt-1">{formatCurrency(totalRetainage)}</div>
          </div>
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-gray-500 text-sm">
              <DollarSign className="h-4 w-4" />
              Remaining
            </div>
            <div className="text-xl font-bold text-gray-900 mt-1">{formatCurrency(amountRemaining)}</div>
          </div>
          <div className="bg-green-50 rounded-lg p-3">
            <div className="flex items-center gap-2 text-green-600 text-sm">
              <Percent className="h-4 w-4" />
              Billing Progress
            </div>
            <div className="text-xl font-bold text-green-700 mt-1">{percentComplete}%</div>
          </div>
        </div>
      </div>

      {/* G702 Summary */}
      <div className="bg-white border-b border-gray-200 px-4 py-3">
        <div className="flex items-center gap-6 text-sm">
          <span className="text-gray-500">G702 Summary:</span>
          <div className="flex items-center gap-4">
            <div><span className="text-gray-500">Original:</span> <span className="font-medium">{formatCurrency(originalContractAmount)}</span></div>
            <div><span className="text-gray-500">COs:</span> <span className="font-medium text-orange-600">+{formatCurrency(netChangeOrders)}</span></div>
            <div><span className="text-gray-500">Current:</span> <span className="font-medium">{formatCurrency(contractAmount)}</span></div>
            <div><span className="text-gray-500">Disbursed:</span> <span className="font-medium text-green-600">{formatCurrency(amountPaid)}</span></div>
          </div>
        </div>
      </div>

      {/* FilterBar */}
      <div className="bg-white border-b border-gray-200 px-4 py-3">
        <FilterBar
          search={search}
          onSearchChange={setSearch}
          searchPlaceholder="Search draws..."
          tabs={[
            { key: 'all', label: 'All', count: mockDraws.length },
            { key: 'draft', label: 'Draft', count: mockDraws.filter(d => d.status === 'draft').length },
            { key: 'lender_review', label: 'In Review', count: mockDraws.filter(d => ['submitted', 'lender_review', 'internal_review'].includes(d.status)).length },
            { key: 'approved', label: 'Approved', count: mockDraws.filter(d => d.status === 'approved').length },
            { key: 'disbursed', label: 'Disbursed', count: mockDraws.filter(d => d.status === 'disbursed').length },
          ]}
          activeTab={activeTab}
          onTabChange={setActiveTab}
          sortOptions={[
            { value: 'drawNumber', label: 'Draw #' },
            { value: 'amount', label: 'Amount' },
            { value: 'milestone', label: 'Milestone' },
            { value: 'applicationDate', label: 'Date' },
            { value: 'percentComplete', label: '% Complete' },
          ]}
          activeSort={activeSort}
          onSortChange={setActiveSort}
          sortDirection={sortDirection}
          onSortDirectionChange={toggleSortDirection}
          resultCount={filteredDraws.length}
          totalCount={mockDraws.length}
        />
      </div>

      {/* Progress Bar */}
      <div className="bg-white border-b border-gray-200 px-4 py-4">
        <div className="flex items-center gap-4 mb-3">
          <span className="text-sm font-medium text-gray-700">Overall Progress</span>
          <div className="flex items-center gap-3 text-xs text-gray-500">
            <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-green-500 rounded" /><span>Disbursed</span></div>
            <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-amber-500 rounded" /><span>Approved</span></div>
            <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-yellow-400 rounded" /><span>In Review</span></div>
            <div className="flex items-center gap-1.5"><div className="w-3 h-3 bg-gray-300 rounded" /><span>Draft</span></div>
          </div>
        </div>
        <ProgressBar draws={mockDraws} />
      </div>

      {/* Draw Schedule Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-gray-100 border-b border-gray-200">
            <tr>
              <th className="text-left py-3 px-4 font-medium text-gray-600">Draw / Milestone</th>
              <th className="text-right py-3 px-3 font-medium text-gray-600">Amount</th>
              <th className="text-right py-3 px-3 font-medium text-gray-600">Retainage</th>
              <th className="text-right py-3 px-3 font-medium text-gray-600">Net</th>
              <th className="text-center py-3 px-3 font-medium text-gray-600">% Complete</th>
              <th className="text-left py-3 px-3 font-medium text-gray-600">Status</th>
              <th className="text-left py-3 px-3 font-medium text-gray-600">Period</th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-100">
            {filteredDraws.map(draw => (
              <DrawRow
                key={draw.id}
                draw={draw}
                expanded={expandedRows.has(draw.id)}
                onToggle={() => toggleRow(draw.id)}
              />
            ))}
          </tbody>
          <tfoot className="bg-gray-50 border-t-2 border-gray-300">
            <tr className="font-semibold">
              <td className="py-3 px-4 text-gray-900">TOTAL</td>
              <td className="py-3 px-3 text-right text-gray-900">{formatCurrency(contractAmount)}</td>
              <td className="py-3 px-3 text-right text-gray-600">{formatCurrency(totalRetainage)}</td>
              <td className="py-3 px-3 text-right text-gray-900">{formatCurrency(contractAmount - totalRetainage)}</td>
              <td className="py-3 px-3 text-center text-gray-900">100%</td>
              <td colSpan={2} className="py-3 px-3"></td>
            </tr>
          </tfoot>
        </table>
      </div>

      {/* AI Features Panel */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 border-t border-purple-200 px-4 py-4">
        <AIFeaturesPanel
          title="Draw Intelligence"
          features={drawAIFeatures}
          columns={2}
        />
      </div>
    </div>
  )
}
